# Generated by Django 2.2.1 on 2019-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190930_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
