# Generated by Django 2.2.1 on 2019-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191005_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
