# Generated by Django 2.2.1 on 2019-10-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191012_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='images/static/default.png', upload_to='images/'),
        ),
    ]
